-- Deterministic, isolated performance data for PermissionCore.
-- Generated by Generate-SeedSql.ps1. No password or credential is embedded.
USE permacore_iam;

SET @perf_user_target = __USER_TARGET__;
SET @perf_dept_target = __DEPT_TARGET__;
SET @perf_role_target = __ROLE_TARGET__;
SET @perf_permission_target = __PERMISSION_TARGET__;
SET @perf_login_log_target = __LOG_TARGET__;
SET @perf_oper_log_target = __LOG_TARGET__;
SET @perf_login_user_target = 200;
SET @perf_admin_username = '__ADMIN_USERNAME__';
SET @perf_seed_time = TIMESTAMP('2026-01-01 00:00:00');

SET @perf_admin_id = (
  SELECT id FROM sys_user
  WHERE username = @perf_admin_username AND status = 1 AND del_flag = 0
  LIMIT 1
);
SET @perf_admin_hash = (
  SELECT password FROM sys_user WHERE id = @perf_admin_id LIMIT 1
);
SET @perf_admin_role_id = (
  SELECT id FROM sys_role
  WHERE role_key = 'ROLE_ADMIN' AND status = 1 AND del_flag = 0
  LIMIT 1
);

CREATE TEMPORARY TABLE perf_seed_guard (
  ok TINYINT NOT NULL,
  CONSTRAINT chk_perf_seed_guard CHECK (ok = 1)
) ENGINE=InnoDB;
INSERT INTO perf_seed_guard (ok)
VALUES (IF(@perf_admin_id IS NOT NULL
          AND @perf_admin_role_id IS NOT NULL
          AND CHAR_LENGTH(COALESCE(@perf_admin_hash, '')) >= 20, 1, 0));
DROP TEMPORARY TABLE perf_seed_guard;

START TRANSACTION;

-- Remove only data owned by this seed so reruns are deterministic.
DELETE ur FROM sys_user_role ur
INNER JOIN sys_user u ON u.id = ur.user_id
WHERE u.username LIKE 'perf\\_login\\_%' ESCAPE '\\'
   OR u.username LIKE 'perf\\_user\\_%' ESCAPE '\\';
DELETE rp FROM sys_role_permission rp
INNER JOIN sys_role r ON r.id = rp.role_id
WHERE r.role_key LIKE 'PERF\\_ROLE\\_%' ESCAPE '\\';
DELETE rp FROM sys_role_permission rp
INNER JOIN sys_permission p ON p.id = rp.permission_id
WHERE p.perm_key LIKE 'perf:generated:%';
DELETE ri FROM sys_role_inheritance ri
LEFT JOIN sys_role a ON a.id = ri.ancestor_id
LEFT JOIN sys_role d ON d.id = ri.descendant_id
WHERE a.role_key LIKE 'PERF\\_ROLE\\_%' ESCAPE '\\'
   OR d.role_key LIKE 'PERF\\_ROLE\\_%' ESCAPE '\\';
DELETE FROM sys_login_log WHERE message = 'PERF_SEED';
DELETE FROM sys_oper_log WHERE title = 'PERF_SEED';
DELETE FROM sys_user
WHERE username LIKE 'perf\\_login\\_%' ESCAPE '\\'
   OR username LIKE 'perf\\_user\\_%' ESCAPE '\\';
DELETE FROM sys_permission WHERE perm_key LIKE 'perf:generated:%';
DELETE FROM sys_role WHERE role_key LIKE 'PERF\\_ROLE\\_%' ESCAPE '\\';
DELETE FROM sys_dept WHERE dept_name LIKE 'PERF\\_DEPT\\_%' ESCAPE '\\';

SET @non_perf_users = (SELECT COUNT(*) FROM sys_user WHERE del_flag = 0);
SET @non_perf_depts = (SELECT COUNT(*) FROM sys_dept WHERE del_flag = 0);
SET @non_perf_roles = (SELECT COUNT(*) FROM sys_role WHERE del_flag = 0);
SET @non_perf_permissions = (SELECT COUNT(*) FROM sys_permission);
SET @non_perf_login_logs = (SELECT COUNT(*) FROM sys_login_log);
SET @non_perf_oper_logs = (SELECT COUNT(*) FROM sys_oper_log);

SET @users_to_add = GREATEST(@perf_user_target - @non_perf_users, 0);
SET @depts_to_add = GREATEST(@perf_dept_target - @non_perf_depts, 0);
SET @roles_to_add = GREATEST(@perf_role_target - @non_perf_roles, 0);
SET @permissions_to_add = GREATEST(@perf_permission_target - @non_perf_permissions, 0);
SET @login_logs_to_add = GREATEST(@perf_login_log_target - @non_perf_login_logs, 0);
SET @oper_logs_to_add = GREATEST(@perf_oper_log_target - @non_perf_oper_logs, 0);
SET @numbers_needed = GREATEST(
  @users_to_add * 3,
  @depts_to_add,
  @roles_to_add,
  @permissions_to_add,
  @login_logs_to_add,
  @oper_logs_to_add
);

CREATE TEMPORARY TABLE perf_numbers (n INT NOT NULL PRIMARY KEY) ENGINE=MEMORY;
INSERT INTO perf_numbers (n)
SELECT 1 + a.d + b.d * 10 + c.d * 100 + d.d * 1000 + e.d * 10000 + f.d * 100000
FROM (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
            UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
            UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
            UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
            UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
CROSS JOIN (SELECT 0 d UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
            UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
WHERE a.d + b.d * 10 + c.d * 100 + d.d * 1000 + e.d * 10000 + f.d * 100000 < @numbers_needed;

INSERT INTO sys_dept (
  parent_id, dept_name, dept_path, leader_id, phone, email,
  sort_order, status, create_by, create_time, del_flag
)
SELECT
  0,
  CONCAT('PERF_DEPT_', LPAD(n, 6, '0')),
  CONCAT('/perf/', n),
  NULL,
  CONCAT('021', LPAD(MOD(n, 100000000), 8, '0')),
  CONCAT('perf-dept-', n, '@example.invalid'),
  n,
  1,
  @perf_admin_id,
  DATE_ADD(@perf_seed_time, INTERVAL n SECOND),
  0
FROM perf_numbers
WHERE n <= @depts_to_add;

INSERT INTO sys_role (
  role_key, role_name, role_type, sort_order, status,
  create_by, create_time, remark, del_flag
)
SELECT
  CONCAT('PERF_ROLE_', LPAD(n, 6, '0')),
  CONCAT('Performance Role ', LPAD(n, 6, '0')),
  2,
  1000 + n,
  1,
  @perf_admin_id,
  DATE_ADD(@perf_seed_time, INTERVAL n SECOND),
  'Deterministic performance seed',
  0
FROM perf_numbers
WHERE n <= @roles_to_add;

INSERT INTO sys_permission (
  perm_key, perm_name, resource_type, resource_id,
  parent_id, sort_order, status, create_time
)
SELECT
  CONCAT('perf:generated:', LPAD(n, 6, '0')),
  CONCAT('Performance Permission ', LPAD(n, 6, '0')),
  3,
  n,
  0,
  1000 + n,
  1,
  DATE_ADD(@perf_seed_time, INTERVAL n SECOND)
FROM perf_numbers
WHERE n <= @permissions_to_add;

CREATE TEMPORARY TABLE perf_dept_rank (rn INT NOT NULL PRIMARY KEY, id BIGINT NOT NULL) ENGINE=MEMORY
SELECT ROW_NUMBER() OVER (ORDER BY id) AS rn, id
FROM sys_dept
WHERE dept_name LIKE 'PERF\\_DEPT\\_%' ESCAPE '\\';
CREATE TEMPORARY TABLE perf_role_rank (rn INT NOT NULL PRIMARY KEY, id BIGINT NOT NULL) ENGINE=MEMORY
SELECT ROW_NUMBER() OVER (ORDER BY id) AS rn, id
FROM sys_role
WHERE role_key LIKE 'PERF\\_ROLE\\_%' ESCAPE '\\';
CREATE TEMPORARY TABLE perf_role_rank_parent (rn INT NOT NULL PRIMARY KEY, id BIGINT NOT NULL) ENGINE=MEMORY;
INSERT INTO perf_role_rank_parent (rn, id) SELECT rn, id FROM perf_role_rank;
CREATE TEMPORARY TABLE perf_permission_rank (rn INT NOT NULL PRIMARY KEY, id BIGINT NOT NULL) ENGINE=MEMORY
SELECT ROW_NUMBER() OVER (ORDER BY id) AS rn, id
FROM sys_permission
WHERE perm_key LIKE 'perf:generated:%';

SET @perf_dept_count = (SELECT COUNT(*) FROM perf_dept_rank);
SET @perf_role_count = (SELECT COUNT(*) FROM perf_role_rank);
SET @perf_permission_count = (SELECT COUNT(*) FROM perf_permission_rank);
SET @perf_actor_role_id = (SELECT id FROM perf_role_rank WHERE rn = 1 LIMIT 1);
SET @fallback_dept_id = (SELECT id FROM sys_dept WHERE del_flag = 0 ORDER BY id LIMIT 1);

INSERT INTO sys_user (
  username, password, nickname, email, phone, dept_id, status,
  auth_version, create_by, create_time, remark, del_flag
)
SELECT
  CASE WHEN n <= @perf_login_user_target
       THEN CONCAT('perf_login_', LPAD(n, 4, '0'))
       ELSE CONCAT('perf_user_', LPAD(n, 6, '0')) END,
  CASE WHEN n <= @perf_login_user_target
       THEN @perf_admin_hash
       ELSE CONCAT('!PERF_DISABLED!', LPAD(n, 12, '0')) END,
  CONCAT('Performance User ', LPAD(n, 6, '0')),
  CONCAT('perf-user-', n, '@example.invalid'),
  CONCAT('139', LPAD(MOD(n, 100000000), 8, '0')),
  COALESCE(
    (SELECT id FROM perf_dept_rank
     WHERE rn = 1 + MOD(n - 1, NULLIF(@perf_dept_count, 0))),
    @fallback_dept_id
  ),
  1,
  0,
  @perf_admin_id,
  DATE_ADD(@perf_seed_time, INTERVAL n SECOND),
  'Deterministic synthetic user; not production data',
  0
FROM perf_numbers
WHERE n <= @users_to_add;

CREATE TEMPORARY TABLE perf_user_rank (
  rn INT NOT NULL PRIMARY KEY,
  id BIGINT NOT NULL
) ENGINE=MEMORY
SELECT ROW_NUMBER() OVER (ORDER BY id) AS rn, id
FROM sys_user
WHERE username LIKE 'perf\\_login\\_%' ESCAPE '\\'
   OR username LIKE 'perf\\_user\\_%' ESCAPE '\\';

-- Exactly 200 named login accounts share the runtime bootstrap admin BCrypt hash,
-- but use a dedicated least-privilege load-test role to keep JWT headers bounded.
INSERT IGNORE INTO sys_user_role (user_id, role_id, create_time)
SELECT id, COALESCE(@perf_actor_role_id, @perf_admin_role_id), DATE_ADD(@perf_seed_time, INTERVAL rn SECOND)
FROM perf_user_rank
WHERE rn <= LEAST(@perf_login_user_target, @users_to_add);

-- Non-login users receive three deterministic synthetic roles.
INSERT IGNORE INTO sys_user_role (user_id, role_id, create_time)
SELECT
  u.id,
  r.id,
  DATE_ADD(@perf_seed_time, INTERVAL (u.rn * 3 + slots.slot_no) SECOND)
FROM perf_user_rank u
CROSS JOIN (SELECT 0 AS slot_no UNION ALL SELECT 1 UNION ALL SELECT 2) slots
INNER JOIN perf_role_rank r
  ON r.rn = 1 + MOD((u.rn - 1) * 3 + slots.slot_no, NULLIF(@perf_role_count, 0))
WHERE u.rn > @perf_login_user_target;

-- Give every synthetic role five permissions, producing a non-trivial authorization graph.
INSERT IGNORE INTO sys_role_permission (role_id, permission_id, create_time)
SELECT
  r.id,
  p.id,
  DATE_ADD(@perf_seed_time, INTERVAL (r.rn * 5 + slots.slot_no) SECOND)
FROM perf_role_rank r
CROSS JOIN (
  SELECT 0 AS slot_no UNION ALL SELECT 1 UNION ALL SELECT 2
  UNION ALL SELECT 3 UNION ALL SELECT 4
) slots
INNER JOIN perf_permission_rank p
  ON p.rn = 1 + MOD((r.rn - 1) * 5 + slots.slot_no, NULLIF(@perf_permission_count, 0));

INSERT IGNORE INTO sys_role_permission (role_id, permission_id, create_time)
SELECT @perf_actor_role_id, p.id, @perf_seed_time
FROM sys_permission p
WHERE p.perm_key IN (
  'system:user:query', 'user:assignRole',
  'system:role:query', 'role:assignPermission',
  'system:permission:query', 'system:log:query'
);

-- A direct-edge chain exercises recursive role inheritance without storing a closure table.
INSERT IGNORE INTO sys_role_inheritance (ancestor_id, descendant_id, depth)
SELECT parent_role.id, child_role.id, 1
FROM perf_role_rank child_role
INNER JOIN perf_role_rank_parent parent_role ON parent_role.rn = child_role.rn - 1
WHERE child_role.rn > 1;

INSERT INTO sys_login_log (
  username, ip_address, location, browser, os,
  login_time, status, message
)
SELECT
  CONCAT('perf_login_', LPAD(1 + MOD(n - 1, @perf_login_user_target), 4, '0')),
  CONCAT('198.51.100.', 1 + MOD(n, 254)),
  'Synthetic',
  'k6',
  'Performance Test',
  DATE_ADD(@perf_seed_time, INTERVAL MOD(n, 2678400) SECOND),
  IF(MOD(n, 20) = 0, 0, 1),
  'PERF_SEED'
FROM perf_numbers
WHERE n <= @login_logs_to_add;

INSERT INTO sys_oper_log (
  title, business_type, method, request_method, operator_id,
  operator_name, oper_ip, oper_location, oper_param, json_result,
  status, error_msg, oper_time, cost_time
)
SELECT
  'PERF_SEED',
  MOD(n, 4),
  'com.permacore.iam.performance.SyntheticOperation',
  IF(MOD(n, 4) = 0, 'GET', 'PUT'),
  u.id,
  CASE WHEN u.rn <= @perf_login_user_target
       THEN CONCAT('perf_login_', LPAD(u.rn, 4, '0'))
       ELSE CONCAT('perf_user_', LPAD(u.rn, 6, '0')) END,
  CONCAT('203.0.113.', 1 + MOD(n, 254)),
  'Synthetic',
  CONCAT('{"seed":', n, '}'),
  '{"code":200}',
  IF(MOD(n, 50) = 0, 1, 0),
  IF(MOD(n, 50) = 0, 'Synthetic failure', NULL),
  DATE_ADD(@perf_seed_time, INTERVAL MOD(n, 2678400) SECOND),
  1 + MOD(n, 250)
FROM perf_numbers numbers
INNER JOIN perf_user_rank u
  ON u.rn = 1 + MOD(numbers.n - 1, NULLIF(@users_to_add, 0))
WHERE n <= @oper_logs_to_add;

COMMIT;

ANALYZE TABLE
  sys_dept, sys_user, sys_role, sys_permission,
  sys_user_role, sys_role_permission, sys_role_inheritance,
  sys_login_log, sys_oper_log;

SELECT
  @perf_user_target AS requested_users,
  (SELECT COUNT(*) FROM sys_user WHERE del_flag = 0) AS actual_users,
  @perf_dept_target AS requested_depts,
  (SELECT COUNT(*) FROM sys_dept WHERE del_flag = 0) AS actual_depts,
  @perf_role_target AS requested_roles,
  (SELECT COUNT(*) FROM sys_role WHERE del_flag = 0) AS actual_roles,
  @perf_permission_target AS requested_permissions,
  (SELECT COUNT(*) FROM sys_permission) AS actual_permissions,
  (SELECT COUNT(*) FROM sys_user_role) AS user_role_relations,
  (SELECT COUNT(*) FROM sys_login_log) AS login_logs,
  (SELECT COUNT(*) FROM sys_oper_log) AS oper_logs,
  (SELECT COUNT(*) FROM sys_user WHERE username LIKE 'perf\\_login\\_%' ESCAPE '\\') AS login_accounts;
